"""empty message

Revision ID: 4cb4ee6559a2
Revises: 
Create Date: 2024-08-06 02:08:11.358348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb4ee6559a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('country', sa.Enum('COLOMBIABOGOTA', 'VENEZUELACARACAS', 'ECUADORQUITO', 'PERULIMA', 'BOLIVIALAPAZ', 'MEXICOCDMX', 'CHILESANTIAGO', 'PARAGUAYASUNCION', 'URUGUAYMONTEVIDEO', 'ARGENTINABSAS', name='country'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('user_music_gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('music_gender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_gender_id'], ['music_gender.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_music_gender')
    op.drop_table('user')
    op.drop_table('music_gender')
    # ### end Alembic commands ###
