"""empty message

Revision ID: 696350ca7df7
Revises: 88d706d2e40a
Create Date: 2024-08-22 02:20:21.214852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696350ca7df7'
down_revision = '88d706d2e40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_from_id', sa.Integer(), nullable=True),
    sa.Column('user_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('connect_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connect_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='connect_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='connect_users_pkey')
    )
    op.drop_table('follow')
    # ### end Alembic commands ###
