"""empty message

Revision ID: 7d2c83afc725
Revises: a41f371a91ae
Create Date: 2024-08-03 02:10:25.243924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d2c83afc725'
down_revision = 'a41f371a91ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('music_gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_gender', postgresql.ENUM('ROCK', 'JAZZ', 'URBAN', 'BLUES', 'CLASSIC', 'FOLKLORE', 'ELECTRO', 'REGGAE', 'METAL', 'INDIE', name='musicgender'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
