"""empty message

Revision ID: a41f371a91ae
Revises: 
Create Date: 2024-08-03 02:03:28.064628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41f371a91ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('music_gender', sa.Enum('ROCK', 'JAZZ', 'URBAN', 'BLUES', 'CLASSIC', 'FOLKLORE', 'ELECTRO', 'REGGAE', 'METAL', 'INDIE', name='musicgender'), nullable=False),
    sa.Column('role', sa.Enum('GUITARIST', 'SINGER', 'BASSIST', 'DRUMMER', 'VIOLINIST', 'PIANIST', 'DJ', 'AUDIOENGINEER', 'TRUMPETER', 'UKELELE', name='role'), nullable=False),
    sa.Column('country', sa.Enum('COLOMBIABOGOTA', 'VENEZUELACARACAS', 'ECUADORQUITO', 'PERULIMA', 'BOLIVIALAPAZ', 'MEXICOCDMX', 'CHILESANTIAGO', 'PARAGUAYASUNCION', 'URUGUAYMONTEVIDEO', 'ARGENTINABSAS', name='country'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
